# Generated by Django 5.2.2 on 2025-06-09 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_nomortanding_perguruan_utusan_atlet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bagan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bagan', models.CharField(blank=True, max_length=100, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.event')),
                ('nomor_tanding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.nomortanding')),
            ],
        ),
        migrations.CreateModel(
            name='DetailBagan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('urutan', models.IntegerField()),
                ('atlet1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlet1', to='backend.atlet')),
                ('atlet2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlet2', to='backend.atlet')),
                ('bagan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.bagan')),
            ],
        ),
    ]
