# Generated by Django 5.2.2 on 2025-06-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_bagan_detailbagan'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagan',
            name='hantei',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailbagan',
            name='score1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='detailbagan',
            name='score2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
