# Generated by Django 5.2.2 on 2025-06-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_detailbagan_hantei_detailbagan_score1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagan',
            name='tipe_tanding',
            field=models.CharField(blank=True, choices=[('1', 'Kata'), ('2', 'Kumite')], max_length=20, null=True),
        ),
    ]
