# Generated by Django 5.2.3 on 2025-06-12 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_bagan_tipe_tanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='tatami',
            name='detail_bagan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.detailbagan'),
        ),
    ]
