# Generated by Django 5.2.3 on 2025-06-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_tatami_detail_bagan'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagan',
            name='kata1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='detailbagan',
            name='kata2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
