# Generated by Django 5.2.3 on 2025-06-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_detailbagan_kata1_detailbagan_kata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atlet', models.IntegerField(blank=True, null=True)),
                ('score1', models.CharField(blank=True, max_length=10, null=True)),
                ('score2', models.CharField(blank=True, max_length=10, null=True)),
                ('score3', models.CharField(blank=True, max_length=10, null=True)),
                ('score4', models.CharField(blank=True, max_length=10, null=True)),
                ('score5', models.CharField(blank=True, max_length=10, null=True)),
                ('detail_bagan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.detailbagan')),
            ],
        ),
    ]
