# Generated by Django 5.2.3 on 2025-06-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score1',
            field=models.CharField(blank=True, default='0.0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score2',
            field=models.CharField(blank=True, default='0.0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score3',
            field=models.CharField(blank=True, default='0.0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score4',
            field=models.CharField(blank=True, default='0.0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score5',
            field=models.CharField(blank=True, default='0.0', max_length=10, null=True),
        ),
    ]
