# Generated by Django 5.2.3 on 2025-07-06 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_bagan_juara_1_bagan_juara_2_bagan_juara_3a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailbagan',
            name='kata1',
            field=models.CharField(blank=True, default='0 - Blank', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detailbagan',
            name='kata2',
            field=models.CharField(blank=True, default='0 - Blank', max_length=50, null=True),
        ),
    ]
