# Generated by Django 5.2.3 on 2025-07-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_detailbagan_kata1_alter_detailbagan_kata2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='nama_event',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
