# Generated by Django 5.2.3 on 2025-08-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_event_nama_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagan',
            name='selesai',
            field=models.BooleanField(default=False),
        ),
    ]
