# Generated by Django 5.2.3 on 2025-08-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_detailbagan_selesai'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagan',
            name='round_robin',
            field=models.BooleanField(default=False),
        ),
    ]
