# Generated by Django 5.2.3 on 2025-08-10 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_bagan_round_robin'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagan',
            name='pemenang',
            field=models.CharField(blank=True, choices=[('1', 'Aka'), ('2', 'Ao'), ('3', 'Draw')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detailbagan',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailbagan',
            name='urutan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
