# Generated by Django 5.2.2 on 2025-09-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_detailbagan_pemenang_alter_detailbagan_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagan',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
