# Generated by Django 5.2.2 on 2025-09-15 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_bagan_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagan',
            name='number',
        ),
    ]
