# Generated by Django 5.2.2 on 2025-10-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_remove_bagan_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagan',
            name='vr1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detailbagan',
            name='vr2',
            field=models.BooleanField(default=False),
        ),
    ]
