# Generated by Django 5.2.2 on 2025-10-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_detailbagan_vr1_detailbagan_vr2'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagan',
            name='pool',
            field=models.IntegerField(default=1),
        ),
    ]
