# Generated by Django 5.2.3 on 2026-06-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_matchup'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagan',
            name='team',
            field=models.BooleanField(default=False),
        ),
    ]
