# Generated by Django 5.2.3 on 2026-06-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_detailbagan_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagan',
            name='scorekecil1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='detailbagan',
            name='scorekecil2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
