# Generated by Django 5.2.3 on 2026-07-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_detailbagan_scorekecil1_detailbagan_scorekecil2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sedang_berjalan',
        ),
    ]
