# Generated by Django 5.2.3 on 2026-07-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_remove_event_sedang_berjalan'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagan',
            name='kode',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
