# Generated by Django 5.2.3 on 2026-07-31 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_detailbagan_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagan',
            name='kode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
