# Generated by Django 5.2.3 on 2026-08-01 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_bagan_kode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('row_type', models.CharField(choices=[('slot', 'Slot Waktu'), ('label', 'Label / Break')], default='slot', max_length=10)),
                ('time_label', models.CharField(blank=True, max_length=50)),
                ('label_text', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_rows', to='backend.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TimetableCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.CharField(blank=True, max_length=200)),
                ('nomor_tanding', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.nomortanding')),
                ('tatami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tatami')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='backend.timetablerow')),
            ],
            options={
                'unique_together': {('row', 'tatami')},
            },
        ),
    ]
