# Generated by Django 5.2.3 on 2026-08-01 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_remove_timetablerow_event_timetableday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KopSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='kop_surat_logos/')),
                ('nama_organisasi', models.CharField(blank=True, max_length=200)),
                ('alamat', models.CharField(blank=True, max_length=300)),
                ('kontak', models.CharField(blank=True, max_length=200)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kop_surat', to='backend.event')),
            ],
        ),
    ]
