# Generated by Django 5.2.3 on 2026-08-01 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_kopsurat'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventKeterangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='keterangan', to='backend.event')),
            ],
        ),
    ]
