# Generated by Django 5.2.3 on 2026-08-12 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_eventketerangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlet',
            name='utusan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlet', to='backend.utusan'),
        ),
    ]
