# Generated by Django 5.2.2 on 2026-08-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_alter_atlet_utusan'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlet',
            name='nik',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
