# Generated by Django 5.2.3 on 2026-09-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='kode_event',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
