# Generated by Django 5.2.3 on 2026-09-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_syncqueue'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='atlet',
            index=models.Index(fields=['event', 'nama_atlet'], name='backend_atl_event_i_4d7470_idx'),
        ),
        migrations.AddIndex(
            model_name='atlet',
            index=models.Index(fields=['event', 'nomor_tanding'], name='backend_atl_event_i_a34e1e_idx'),
        ),
        migrations.AddIndex(
            model_name='bagan',
            index=models.Index(fields=['event', 'kode'], name='backend_bag_event_i_7624f6_idx'),
        ),
        migrations.AddIndex(
            model_name='bagan',
            index=models.Index(fields=['event', 'nomor_tanding'], name='backend_bag_event_i_8d2e14_idx'),
        ),
        migrations.AddIndex(
            model_name='detailbagan',
            index=models.Index(fields=['bagan', 'round', 'urutan'], name='backend_det_bagan_i_164bdb_idx'),
        ),
    ]
