# Generated by Django 5.2.3 on 2026-09-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_atlet_backend_atl_event_i_4d7470_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlet',
            name='kode_atlet',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='atlet',
            index=models.Index(fields=['event', 'kode_atlet'], name='backend_atl_event_i_f95714_idx'),
        ),
    ]
