# Generated by Django 5.2 on 2026-09-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_atlet_kode_atlet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagan',
            name='is_bob',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nomortanding',
            name='is_bob',
            field=models.BooleanField(default=False),
        ),
    ]
