# Generated by Django 5.2 on 2026-09-15 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_bagan_is_bob_nomortanding_is_bob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wasit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_wasit', models.CharField(max_length=100)),
                ('lisensi', models.CharField(blank=True, max_length=50, null=True)),
                ('no_lisensi', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wasits', to='backend.event')),
                ('perguruan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wasits', to='backend.perguruan')),
            ],
            options={
                'ordering': ['nama_wasit'],
            },
        ),
        migrations.CreateModel(
            name='WasitTatami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(choices=[('tatami_manager', 'Tatami Manager'), ('referee', 'Wasit Utama (Referee)'), ('judge_1', 'Juri 1 (Judge 1)'), ('judge_2', 'Juri 2 (Judge 2)'), ('judge_3', 'Juri 3 (Judge 3)'), ('judge_4', 'Juri 4 (Judge 4)'), ('kansa', 'Kansa (Match Supervisor)'), ('pool', 'Anggota Pool Tatami')], default='pool', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wasit_tatamis', to='backend.event')),
                ('tatami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wasit_assignments', to='backend.tatami')),
                ('wasit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tatami_assignments', to='backend.wasit')),
            ],
            options={
                'ordering': ['posisi', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='wasit',
            index=models.Index(fields=['event', 'nama_wasit'], name='backend_was_event_i_24e3c5_idx'),
        ),
        migrations.AddIndex(
            model_name='wasit',
            index=models.Index(fields=['event', 'perguruan'], name='backend_was_event_i_27975d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wasittatami',
            unique_together={('tatami', 'wasit')},
        ),
    ]
