# Generated by Django 5.2 on 2026-09-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_wasit_wasittatami_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasit',
            name='kab_kota',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kabupaten/Kota'),
        ),
        migrations.AlterField(
            model_name='wasittatami',
            name='posisi',
            field=models.CharField(choices=[('tatami_manager', 'Tatami Manager'), ('referee', 'Wasit Utama (Referee)'), ('wasit_2', 'Wasit 2 (Assistant Referee)'), ('judge_1', 'Juri 1 (Judge 1)'), ('judge_2', 'Juri 2 (Judge 2)'), ('judge_3', 'Juri 3 (Judge 3)'), ('judge_4', 'Juri 4 (Judge 4)'), ('judge_5', 'Juri 5 (Judge 5)'), ('judge_6', 'Juri 6 (Judge 6)'), ('judge_7', 'Juri 7 (Judge 7)'), ('kansa', 'Kansa (Match Supervisor)'), ('pool', 'Anggota Pool Tatami')], default='pool', max_length=30),
        ),
    ]
