# Generated by Django 5.2.3 on 2026-09-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_wasit_kab_kota_alter_wasittatami_posisi'),
    ]

    operations = [
        migrations.AddField(
            model_name='utusan',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo_utusan/'),
        ),
    ]
