# Generated by Django 5.2.2 on 2026-09-19 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_utusan_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_live_sync_enabled',
            field=models.BooleanField(default=False, verbose_name='Live Sync Aktif'),
        ),
        migrations.AddField(
            model_name='syncqueue',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue_items', to='backend.event'),
        ),
    ]
