# Generated by Django 5.2.2 on 2026-09-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_event_is_live_sync_enabled_syncqueue_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagan',
            name='has_vr',
            field=models.BooleanField(default=False, verbose_name='Bagan Memiliki VR'),
        ),
        migrations.AddField(
            model_name='nomortanding',
            name='has_vr',
            field=models.BooleanField(default=False, verbose_name='Video Review (VR)'),
        ),
    ]
