# Generated by Django 5.2 on 2026-09-23 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_bagan_has_vr_nomortanding_has_vr'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbagan',
            name='assigned_tatami',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_matches', to='backend.tatami'),
        ),
        migrations.CreateModel(
            name='WasitDetailBagan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posisi', models.CharField(choices=[('tatami_manager', 'Tatami Manager'), ('referee', 'Wasit Utama (Referee)'), ('wasit_2', 'Wasit 2 (Assistant Referee)'), ('judge_1', 'Juri 1 (Judge 1)'), ('judge_2', 'Juri 2 (Judge 2)'), ('judge_3', 'Juri 3 (Judge 3)'), ('judge_4', 'Juri 4 (Judge 4)'), ('judge_5', 'Juri 5 (Judge 5)'), ('judge_6', 'Juri 6 (Judge 6)'), ('judge_7', 'Juri 7 (Judge 7)'), ('kansa', 'Kansa (Match Supervisor)'), ('pool', 'Anggota Pool Tatami')], default='pool', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('detail_bagan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wasit_assignments', to='backend.detailbagan')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wasit_detail_bagans', to='backend.event')),
                ('wasit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_assignments', to='backend.wasit')),
            ],
            options={
                'ordering': ['posisi', 'id'],
                'indexes': [models.Index(fields=['detail_bagan', 'posisi'], name='backend_was_detail__97c529_idx'), models.Index(fields=['event', 'wasit'], name='backend_was_event_i_299e44_idx')],
                'unique_together': {('detail_bagan', 'wasit')},
            },
        ),
    ]
