# Generated by Django 5.2 on 2026-09-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_detailbagan_assigned_tatami_wasitdetailbagan'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlet',
            name='additional_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='atlet',
            name='is_priority',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='atlet',
            index=models.Index(fields=['event', 'additional_code'], name='backend_atl_event_i_edfe5d_idx'),
        ),
    ]
