# Generated by Django 5.2 on 2026-09-28 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_atlet_additional_code_atlet_is_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bagan',
            name='peringkat_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peringkat5', to='backend.atlet'),
        ),
        migrations.AddField(
            model_name='bagan',
            name='peringkat_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peringkat6', to='backend.atlet'),
        ),
        migrations.AddField(
            model_name='bagan',
            name='peringkat_7',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peringkat7', to='backend.atlet'),
        ),
        migrations.AddField(
            model_name='bagan',
            name='peringkat_8',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peringkat8', to='backend.atlet'),
        ),
    ]
